[console]
    title = "Minecraft Server" # nombre de la consola
    server-path = "./" # carpeta del server
    restart-loop = true
    auto-start = false
    auto-eula = true
    wait-mode = "WAIT"
    wait-timer = 30
    exit-on-stop = true
[server]
    jar-name = "purpur-1.16.5-1171.jar"
    jar-path = "./"
    eula-skip = false
    before_jar = ""
    parameters = "-nogui"
[java]
    java-binary = "C:\\Program Files\\Eclipse Adoptium\\jdk-16.0.2.7-hotspot\\bin\\java.exe"
    #java-binary = "C://Program Files//Eclipse Foundation//jdk-16.0.2.7-hotspot//bin//java.exe" # Set java to default java version
    heap-unit = "MB"
    max-memory = 4096
    min-memory = 4096
    memory-percent = 100
    [flags]
        defaults = """-XX:+DisableExplicitGC"""
        enabled = "test, test2"
        [test]
            flags = """
            -XX:+UseG1GC
            -XX:+UnlockExperimentalVMOptions
            """
        [test2]
            flags = """
            -XX:+ParallelRefProcEnabled
            -XX:+AlwaysPreTouch
            """
        [g1gc2]
            flags = """
            -XX:+UseG1GC
            -XX:+UnlockExperimentalVMOptions
            -XX:+ParallelRefProcEnabled
            -XX:+AlwaysPreTouch
            -XX:+PerfDisableSharedMem
            -XX:InitiatingHeapOccupancyPercent=15
            -XX:SurvivorRatio=32
            -XX:MaxTenuringThreshold=1
            -XX:MaxGCPauseMillis=200
            -XX:G1NewSizePercent=30
            -XX:G1MaxNewSizePercent=40
            -XX:G1HeapRegionSize=8M
            -XX:G1ReservePercent=20
            -XX:G1HeapWastePercent=5
            -XX:G1MixedGCCountTarget=4
            -XX:G1MixedGCLiveThresholdPercent=90
            -XX:G1RSetUpdatingPauseTimePercent=5
            -Dusing.aikars.flags=https://mcflags.emc.gs
            -Daikars.new.flags=true
            """
        [zgc]
            flags = """
            -XX:+UseZGC
            -XX:+UnlockExperimentalVMOptions
            -XX:+ParallelRefProcEnabled
            -XX:+AlwaysPreTouch
            -XX:+PerfDisableSharedMem
            -XX:InitiatingHeapOccupancyPercent=15
            -XX:SurvivorRatio=32
            -XX:MaxTenuringThreshold=1
            -XX:-UseG1GC
            -XX:-UseParallelGC
            -Dusing.aikars.flags=https://mcflags.emc.gs
            -Daikars.new.flags=true
            """